import:
  - turbonomic/minions:travis/secrets/.turbo-go-sdk.yml@travis

language: go


go:
  - 1.21.4

go_import_path: github.ibm.com/turbonomic/turbo-go-sdk

env:
  global:
  - MAVEN_OPTS="-Xms1024m -Xmx4096m"
  - TZ=America/New_York
  - secure: UqI4P6n0NNSrk86rbYrm8vCey3eeczzTQ2eb8sDdPSgSkVTMKSck3Np6a4xqWqLiuIU855Gy+AZ83xWsNR8f1HzrVohFAYh7eQEDNcKiNb2PJK+AA00ybf63Y81Cm1ECrdNL/JDfMozk+jjKlIR7B8Zr79hFuuOAH050BVTB1cwo1j/bUKDy4hhyQo9ypa9ycGd2n7Y249ANHDuYYVLK4LvNQdgDh2mpJT+Cm02BP+J+74qpwqGgduhlhUwGvcf936dYKLo/culmb5qQb/RwklpeLOsEGqd9yFIHfYDYShBgjY7ca7PjxJGgHbY7sHslost7ct4nfa4gcbwqER7q8cOY+dYGfHIGn+qoMXFOe7CkTdz+n1PPIqmqZtkKA+9GpuYvd7dujALBD4dLbp6GrVCvIb4A3LZGOAcxAFRkyurWgIcSDPYaDTFzz2GZe+NixKO6pcuOh6ydMIDgKiCcIgcYHLv9u5CGGqFqPpng19KOatSXtCO+iBo17ACfymTQKmFAdJiM9Nyx9HqtbKtX7ba9TlGNHrtMAiwffHG6nijY3DwNHX13qHTiENq88z9iCiaAzQO1bz3ruNVdlU8UmUEOjiOkbKFoO8jRI0tMgyBgfHIOJ9q+g/McG87BLxs2YljJAmL9FMp76qlIgqz4Pc/etPOfgmnXiDQjP1umuFc=
  - secure: HZ7ite6KfrdOo4RG72FbQqvXD+sN62z2d3elo3T5zOlfVgSMLhB7bzVnCjlgvyZsJE5TstWaCyNOextMjWg4p7n7vinf/vk2W/Khi5YJmB3x4WGyEkbO4IUwNREtCanlYNpWEM7sMnnsbLH73nuC4172xtSbV4qbbUTw935EyRezRCvRiw73ahSwhYwdmdiRCObzt678NlR1tA6PRZNWY/F1DI05tvC0vaF1Mj2FkDzwzx0g2ENjfNdM2zSXwFQPvooosDkiympqsKpdh6DuO5eLkMCqI5Tt4+N3TbpSiNRus6w9mkhTM4NTHx4wBiQAkaF+aNFBbozqmx8F5DGfJtVEZL6BQ70fBVWE0APem4p4g9TiUf6WLzT1goc67vqXXL7At7Z0ki8tqj3G7uS8rnzTTgbb2zXg1eKeUAT9RF0xysIXqfedvqCkH7BRa21wwcdOLnzkyxk/PQcs548k9usJQVXCJZj99RNkFZqUmSBhKuxMeh1t2ZuLgHO5U2XwoudTw38RVsT20nvVcjvCwgr228wblYjIisbLsETT8n0Hck6r5a5HifUaYmRdSadOV7O6dYEiFAnu1d4V98M0jm3S0LBvWk/cGY9vpkT0vxUG/7kPuDocttLeTa60VxtOr3M5WV/v4t7LiyuGOceEClrz0KW6wqe6Aaf6k2wH5q0=
  - secure: bYEzg6PVMOn+E/xVwv853NptOK8WlWmEwMTlf3ANJWXZ16nujfwxYPYObpBhbEuwEKrHVKkJnweBRVcCHh9YgcE+IjlxpIgYuG7r99gFbgLmVMw7xqOdktGczSdu8qIzpzrLLD7RXfN4JGQZrN2SY7RP4xfEeTAOEBfCs+eCMnKq8xJW9KPTR5Rep55QW5hU095gcfCpNtRteNbdOf2Rngek4tk+4Vu6c4mTJseezSc0BAzWtXEm/YSHHYCEywKjZj4XrH4JKIB3JWCTjiZ6TwxAgPA4MtDVHG0vYPqPXqxevb0rjIgu/XFrEwClyaBGUDH0gqtbMCRs1UXqSuTQNZK8m+3H5j5yr0IeHgRsS7Qhkp7Rp5Zy9gAbAipAo8A/eAn5NWyDVK++P4OYJyWiw/M/GYIa1+Fyqh83LBXkRqtzDkrpYbTqXEcba0pk0BB+UWtMEyU8vx4c20OBiUGSaKskU/0IQ1a9fxGoY2qCkIazI1BbKD1zj5PJmGlK3Jq2N+nUhJPP1HJJjxlg+S26yXPUXh5auFCUFyACdLvzmaX5hZ+T5Oxb/Y5tc1wn0DsjCNQtKXXBH/VtjQqjjMNuyTwCo3dGD54BECIZswVN0mgM/r9frjU9QLpmbfU9iWGnGDcWbmaWzQ8pQenU+7xxUCKvnvHfCpYdR3svyU6/6QA=

before_install:
  - rm -rf /home/travis/.netrc
  - |
    cat > /home/travis/.netrc << EOL
    machine github.ibm.com
    login ${GH_USER}
    password ${GH_TOKEN}
    EOL

install: skip

stages:
  - name: deploy
    if: type = push OR type = cron
  - name: pull-request-build
    if: type = pull_request

jobs:
  include:
    - stage: pull-request-build
      script:
        - make check-upstream-dependencies
        - echo "Golang Build" && echo -e 'travis_fold:start:goLangBuild\\r'
        - make fmtcheck
        - make test
        - echo -e 'travis_fold:end:goLangBuild\\r'
      after_success: skip

    - stage: deploy
      script:
        - echo "Golang Build" && echo -e 'travis_fold:start:goLangBuild\\r'
        - make fmtcheck
        - make test
        - make build
        - echo -e 'travis_fold:end:goLangBuild\\r'
      after_success: skip
