// Code generated by protoc-gen-go.
// source: Discovery.proto
// DO NOT EDIT!

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// The types of discovery supported by SDK framework. FULL discovery is supported by default.
type DiscoveryType int32

const (
	// Full discovery which discovers everything
	DiscoveryType_FULL DiscoveryType = 0
	// Incremetal discovery which discovers changed entities (removed, added, etc.)
	DiscoveryType_INCREMENTAL DiscoveryType = 1
	// Performance discovery which discovers utilization data
	DiscoveryType_PERFORMANCE DiscoveryType = 2
)

var DiscoveryType_name = map[int32]string{
	0: "FULL",
	1: "INCREMENTAL",
	2: "PERFORMANCE",
}
var DiscoveryType_value = map[string]int32{
	"FULL":        0,
	"INCREMENTAL": 1,
	"PERFORMANCE": 2,
}

func (x DiscoveryType) Enum() *DiscoveryType {
	p := new(DiscoveryType)
	*p = x
	return p
}
func (x DiscoveryType) String() string {
	return proto.EnumName(DiscoveryType_name, int32(x))
}
func (x *DiscoveryType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(DiscoveryType_value, data, "DiscoveryType")
	if err != nil {
		return err
	}
	*x = DiscoveryType(value)
	return nil
}
func (DiscoveryType) EnumDescriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

// Enum, determining the type of primitive value. All the primitive values are
// always stored in string value holder, but are interpreted differently
type CustomAccountDefEntry_PrimitiveValue int32

const (
	// Value should be interpreted as string
	CustomAccountDefEntry_STRING CustomAccountDefEntry_PrimitiveValue = 1
	// Value should be interpreted as numeric
	CustomAccountDefEntry_NUMERIC CustomAccountDefEntry_PrimitiveValue = 2
	// Value should be interpreted as boolean
	CustomAccountDefEntry_BOOLEAN CustomAccountDefEntry_PrimitiveValue = 3
)

var CustomAccountDefEntry_PrimitiveValue_name = map[int32]string{
	1: "STRING",
	2: "NUMERIC",
	3: "BOOLEAN",
}
var CustomAccountDefEntry_PrimitiveValue_value = map[string]int32{
	"STRING":  1,
	"NUMERIC": 2,
	"BOOLEAN": 3,
}

func (x CustomAccountDefEntry_PrimitiveValue) Enum() *CustomAccountDefEntry_PrimitiveValue {
	p := new(CustomAccountDefEntry_PrimitiveValue)
	*p = x
	return p
}
func (x CustomAccountDefEntry_PrimitiveValue) String() string {
	return proto.EnumName(CustomAccountDefEntry_PrimitiveValue_name, int32(x))
}
func (x *CustomAccountDefEntry_PrimitiveValue) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CustomAccountDefEntry_PrimitiveValue_value, data, "CustomAccountDefEntry_PrimitiveValue")
	if err != nil {
		return err
	}
	*x = CustomAccountDefEntry_PrimitiveValue(value)
	return nil
}
func (CustomAccountDefEntry_PrimitiveValue) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor3, []int{7, 0}
}

type ErrorDTO_ErrorSeverity int32

const (
	ErrorDTO_CRITICAL ErrorDTO_ErrorSeverity = 0
	ErrorDTO_WARNING  ErrorDTO_ErrorSeverity = 1
)

var ErrorDTO_ErrorSeverity_name = map[int32]string{
	0: "CRITICAL",
	1: "WARNING",
}
var ErrorDTO_ErrorSeverity_value = map[string]int32{
	"CRITICAL": 0,
	"WARNING":  1,
}

func (x ErrorDTO_ErrorSeverity) Enum() *ErrorDTO_ErrorSeverity {
	p := new(ErrorDTO_ErrorSeverity)
	*p = x
	return p
}
func (x ErrorDTO_ErrorSeverity) String() string {
	return proto.EnumName(ErrorDTO_ErrorSeverity_name, int32(x))
}
func (x *ErrorDTO_ErrorSeverity) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ErrorDTO_ErrorSeverity_value, data, "ErrorDTO_ErrorSeverity")
	if err != nil {
		return err
	}
	*x = ErrorDTO_ErrorSeverity(value)
	return nil
}
func (ErrorDTO_ErrorSeverity) EnumDescriptor() ([]byte, []int) { return fileDescriptor3, []int{9, 0} }

// Type of the serialized data
type CustomMetadataDTO_Type int32

const (
	CustomMetadataDTO_JSON CustomMetadataDTO_Type = 0
	CustomMetadataDTO_XML  CustomMetadataDTO_Type = 1
)

var CustomMetadataDTO_Type_name = map[int32]string{
	0: "JSON",
	1: "XML",
}
var CustomMetadataDTO_Type_value = map[string]int32{
	"JSON": 0,
	"XML":  1,
}

func (x CustomMetadataDTO_Type) Enum() *CustomMetadataDTO_Type {
	p := new(CustomMetadataDTO_Type)
	*p = x
	return p
}
func (x CustomMetadataDTO_Type) String() string {
	return proto.EnumName(CustomMetadataDTO_Type_name, int32(x))
}
func (x *CustomMetadataDTO_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CustomMetadataDTO_Type_value, data, "CustomMetadataDTO_Type")
	if err != nil {
		return err
	}
	*x = CustomMetadataDTO_Type(value)
	return nil
}
func (CustomMetadataDTO_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor3, []int{10, 0} }

// ValidateResponse is the response of a ValidateRequest message.
// It contains the response, and any errors encountered during the target validation attempt.
type ValidationResponse struct {
	// Errors, discovered during external probe operation
	ErrorDTO         []*ErrorDTO `protobuf:"bytes,1,rep,name=errorDTO" json:"errorDTO,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *ValidationResponse) Reset()                    { *m = ValidationResponse{} }
func (m *ValidationResponse) String() string            { return proto.CompactTextString(m) }
func (*ValidationResponse) ProtoMessage()               {}
func (*ValidationResponse) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

func (m *ValidationResponse) GetErrorDTO() []*ErrorDTO {
	if m != nil {
		return m.ErrorDTO
	}
	return nil
}

// We define which entities with which action types must be merged.
type ActionMergeSpec struct {
	// Incoming action spec
	// The list of entities for which the actions must be merged.
	// They are to be matched to the EntityDTO.id.
	EntityIds []string `protobuf:"bytes,1,rep,name=entity_ids,json=entityIds" json:"entity_ids,omitempty"`
	// Outgoing action spec
	// Target entity
	TargetEntity      *string `protobuf:"bytes,2,opt,name=target_entity,json=targetEntity" json:"target_entity,omitempty"`
	TargetDescription *string `protobuf:"bytes,3,opt,name=target_description,json=targetDescription" json:"target_description,omitempty"`
	// Types that are valid to be assigned to ActionSpec:
	//	*ActionMergeSpec_MoveSpec
	//	*ActionMergeSpec_ResizeSpec
	//	*ActionMergeSpec_ProvisionSpec
	ActionSpec       isActionMergeSpec_ActionSpec `protobuf_oneof:"actionSpec"`
	XXX_unrecognized []byte                       `json:"-"`
}

func (m *ActionMergeSpec) Reset()                    { *m = ActionMergeSpec{} }
func (m *ActionMergeSpec) String() string            { return proto.CompactTextString(m) }
func (*ActionMergeSpec) ProtoMessage()               {}
func (*ActionMergeSpec) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

type isActionMergeSpec_ActionSpec interface {
	isActionMergeSpec_ActionSpec()
}

type ActionMergeSpec_MoveSpec struct {
	MoveSpec *MoveTransformSpec `protobuf:"bytes,4,opt,name=moveSpec,oneof"`
}
type ActionMergeSpec_ResizeSpec struct {
	ResizeSpec *ResizeTransformSpec `protobuf:"bytes,5,opt,name=resizeSpec,oneof"`
}
type ActionMergeSpec_ProvisionSpec struct {
	ProvisionSpec *ProvisionTransformSpec `protobuf:"bytes,6,opt,name=provisionSpec,oneof"`
}

func (*ActionMergeSpec_MoveSpec) isActionMergeSpec_ActionSpec()      {}
func (*ActionMergeSpec_ResizeSpec) isActionMergeSpec_ActionSpec()    {}
func (*ActionMergeSpec_ProvisionSpec) isActionMergeSpec_ActionSpec() {}

func (m *ActionMergeSpec) GetActionSpec() isActionMergeSpec_ActionSpec {
	if m != nil {
		return m.ActionSpec
	}
	return nil
}

func (m *ActionMergeSpec) GetEntityIds() []string {
	if m != nil {
		return m.EntityIds
	}
	return nil
}

func (m *ActionMergeSpec) GetTargetEntity() string {
	if m != nil && m.TargetEntity != nil {
		return *m.TargetEntity
	}
	return ""
}

func (m *ActionMergeSpec) GetTargetDescription() string {
	if m != nil && m.TargetDescription != nil {
		return *m.TargetDescription
	}
	return ""
}

func (m *ActionMergeSpec) GetMoveSpec() *MoveTransformSpec {
	if x, ok := m.GetActionSpec().(*ActionMergeSpec_MoveSpec); ok {
		return x.MoveSpec
	}
	return nil
}

func (m *ActionMergeSpec) GetResizeSpec() *ResizeTransformSpec {
	if x, ok := m.GetActionSpec().(*ActionMergeSpec_ResizeSpec); ok {
		return x.ResizeSpec
	}
	return nil
}

func (m *ActionMergeSpec) GetProvisionSpec() *ProvisionTransformSpec {
	if x, ok := m.GetActionSpec().(*ActionMergeSpec_ProvisionSpec); ok {
		return x.ProvisionSpec
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ActionMergeSpec) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ActionMergeSpec_OneofMarshaler, _ActionMergeSpec_OneofUnmarshaler, _ActionMergeSpec_OneofSizer, []interface{}{
		(*ActionMergeSpec_MoveSpec)(nil),
		(*ActionMergeSpec_ResizeSpec)(nil),
		(*ActionMergeSpec_ProvisionSpec)(nil),
	}
}

func _ActionMergeSpec_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ActionMergeSpec)
	// actionSpec
	switch x := m.ActionSpec.(type) {
	case *ActionMergeSpec_MoveSpec:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.MoveSpec); err != nil {
			return err
		}
	case *ActionMergeSpec_ResizeSpec:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ResizeSpec); err != nil {
			return err
		}
	case *ActionMergeSpec_ProvisionSpec:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ProvisionSpec); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("ActionMergeSpec.ActionSpec has unexpected type %T", x)
	}
	return nil
}

func _ActionMergeSpec_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ActionMergeSpec)
	switch tag {
	case 4: // actionSpec.moveSpec
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(MoveTransformSpec)
		err := b.DecodeMessage(msg)
		m.ActionSpec = &ActionMergeSpec_MoveSpec{msg}
		return true, err
	case 5: // actionSpec.resizeSpec
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ResizeTransformSpec)
		err := b.DecodeMessage(msg)
		m.ActionSpec = &ActionMergeSpec_ResizeSpec{msg}
		return true, err
	case 6: // actionSpec.provisionSpec
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ProvisionTransformSpec)
		err := b.DecodeMessage(msg)
		m.ActionSpec = &ActionMergeSpec_ProvisionSpec{msg}
		return true, err
	default:
		return false, nil
	}
}

func _ActionMergeSpec_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ActionMergeSpec)
	// actionSpec
	switch x := m.ActionSpec.(type) {
	case *ActionMergeSpec_MoveSpec:
		s := proto.Size(x.MoveSpec)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ActionMergeSpec_ResizeSpec:
		s := proto.Size(x.ResizeSpec)
		n += proto.SizeVarint(5<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ActionMergeSpec_ProvisionSpec:
		s := proto.Size(x.ProvisionSpec)
		n += proto.SizeVarint(6<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type ProvisionTransformSpec struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *ProvisionTransformSpec) Reset()                    { *m = ProvisionTransformSpec{} }
func (m *ProvisionTransformSpec) String() string            { return proto.CompactTextString(m) }
func (*ProvisionTransformSpec) ProtoMessage()               {}
func (*ProvisionTransformSpec) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{2} }

type MoveTransformSpec struct {
	// provider for the move
	ProviderType     *EntityDTO_EntityType `protobuf:"varint,1,req,name=providerType,enum=common_dto.EntityDTO_EntityType" json:"providerType,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *MoveTransformSpec) Reset()                    { *m = MoveTransformSpec{} }
func (m *MoveTransformSpec) String() string            { return proto.CompactTextString(m) }
func (*MoveTransformSpec) ProtoMessage()               {}
func (*MoveTransformSpec) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{3} }

func (m *MoveTransformSpec) GetProviderType() EntityDTO_EntityType {
	if m != nil && m.ProviderType != nil {
		return *m.ProviderType
	}
	return EntityDTO_SWITCH
}

type ResizeTransformSpec struct {
	// Specifies the commodity to be changed.
	CommodityType []CommodityDTO_CommodityType `protobuf:"varint,1,rep,name=commodity_type,json=commodityType,enum=common_dto.CommodityDTO_CommodityType" json:"commodity_type,omitempty"`
	// The type of the changed attribute.
	ChangedAttr      []ActionItemDTO_CommodityAttribute `protobuf:"varint,2,rep,name=changed_attr,json=changedAttr,enum=common_dto.ActionItemDTO_CommodityAttribute" json:"changed_attr,omitempty"`
	XXX_unrecognized []byte                             `json:"-"`
}

func (m *ResizeTransformSpec) Reset()                    { *m = ResizeTransformSpec{} }
func (m *ResizeTransformSpec) String() string            { return proto.CompactTextString(m) }
func (*ResizeTransformSpec) ProtoMessage()               {}
func (*ResizeTransformSpec) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{4} }

func (m *ResizeTransformSpec) GetCommodityType() []CommodityDTO_CommodityType {
	if m != nil {
		return m.CommodityType
	}
	return nil
}

func (m *ResizeTransformSpec) GetChangedAttr() []ActionItemDTO_CommodityAttribute {
	if m != nil {
		return m.ChangedAttr
	}
	return nil
}

// The message identifying the probe-specified action merge and transformation specifications.
type DiscoveredActionSpec struct {
	// The list of action merge and transform spec.
	Specs            []*ActionMergeSpec `protobuf:"bytes,1,rep,name=specs" json:"specs,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *DiscoveredActionSpec) Reset()                    { *m = DiscoveredActionSpec{} }
func (m *DiscoveredActionSpec) String() string            { return proto.CompactTextString(m) }
func (*DiscoveredActionSpec) ProtoMessage()               {}
func (*DiscoveredActionSpec) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{5} }

func (m *DiscoveredActionSpec) GetSpecs() []*ActionMergeSpec {
	if m != nil {
		return m.Specs
	}
	return nil
}

// Mediation container response for target discovery request. Holds both errors and discovered
// entities. If errors occurred, any entities can be sent nevertheless. Only those entities should
// be updated in the operations manager.
//
// Errors do not prevent anything. They are just displayed to users in the UI
type DiscoveryResponse struct {
	// Errors, discovered during external probe operation
	ErrorDTO []*ErrorDTO `protobuf:"bytes,1,rep,name=errorDTO" json:"errorDTO,omitempty"`
	// Entities, discovered by external probe.
	EntityDTO []*EntityDTO `protobuf:"bytes,2,rep,name=entityDTO" json:"entityDTO,omitempty"`
	// Constraints defined in external probe
	DiscoveredGroup []*GroupDTO `protobuf:"bytes,3,rep,name=discoveredGroup" json:"discoveredGroup,omitempty"`
	// ServiceEntityProfile (template)
	EntityProfile []*EntityProfileDTO `protobuf:"bytes,4,rep,name=entityProfile" json:"entityProfile,omitempty"`
	// Deployment Profile (ServiceCatalogItem)
	DeploymentProfile []*DeploymentProfileDTO `protobuf:"bytes,5,rep,name=deploymentProfile" json:"deploymentProfile,omitempty"`
	// Notifications for global (not entity-specific) events
	Notification []*NotificationDTO `protobuf:"bytes,6,rep,name=notification" json:"notification,omitempty"`
	// Custom Metadata DTO
	MetadataDTO []*CustomMetadataDTO `protobuf:"bytes,7,rep,name=metadataDTO" json:"metadataDTO,omitempty"`
	// Derived targets' creation requests
	DerivedTarget []*DerivedTargetSpecificationDTO `protobuf:"bytes,8,rep,name=derivedTarget" json:"derivedTarget,omitempty"`
	// Non market entities, discovered by external probe
	NonMarketEntityDTO []*NonMarketEntityDTO `protobuf:"bytes,9,rep,name=nonMarketEntityDTO" json:"nonMarketEntityDTO,omitempty"`
	// Flows, discovered by external probe
	FlowDTO []*FlowDTO `protobuf:"bytes,11,rep,name=flowDTO" json:"flowDTO,omitempty"`
	// Discovery context contains data that needs to be sent back to the probe in the next
	// discovery request
	DiscoveryContext *DiscoveryContextDTO `protobuf:"bytes,12,opt,name=discoveryContext" json:"discoveryContext,omitempty"`
	// Costs/Spend/Discount for Account, CloudService, Templates etc.
	CostDTO []*CostDataDTO `protobuf:"bytes,13,rep,name=costDTO" json:"costDTO,omitempty"`
	// Price table discovered by the cloud cost probes. (see PricingDTO.proto)
	// The cloud provider is giving us prices for the different services and product offerings that
	// they have available. Different products/options combination leads to a different price.
	// Those prices are used to calculate the bottom-up cost of a specific entity (by adding up
	// the different products that are part of it, like compute,storage,license,ip,...).
	PriceTable *PriceTable `protobuf:"bytes,14,opt,name=priceTable" json:"priceTable,omitempty"`
	// Workflows discovered by external probe (formerly appeared as NonMarketEntityDTOs)
	Workflow []*Workflow `protobuf:"bytes,15,rep,name=workflow" json:"workflow,omitempty"`
	// Indicates no change since the previous discovery.
	NoChange *NoChange `protobuf:"bytes,16,opt,name=no_change,json=noChange" json:"no_change,omitempty"`
	// The optional discovered action spec.
	DiscActionSpec   *DiscoveredActionSpec `protobuf:"bytes,17,opt,name=disc_action_spec,json=discActionSpec" json:"disc_action_spec,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *DiscoveryResponse) Reset()                    { *m = DiscoveryResponse{} }
func (m *DiscoveryResponse) String() string            { return proto.CompactTextString(m) }
func (*DiscoveryResponse) ProtoMessage()               {}
func (*DiscoveryResponse) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{6} }

func (m *DiscoveryResponse) GetErrorDTO() []*ErrorDTO {
	if m != nil {
		return m.ErrorDTO
	}
	return nil
}

func (m *DiscoveryResponse) GetEntityDTO() []*EntityDTO {
	if m != nil {
		return m.EntityDTO
	}
	return nil
}

func (m *DiscoveryResponse) GetDiscoveredGroup() []*GroupDTO {
	if m != nil {
		return m.DiscoveredGroup
	}
	return nil
}

func (m *DiscoveryResponse) GetEntityProfile() []*EntityProfileDTO {
	if m != nil {
		return m.EntityProfile
	}
	return nil
}

func (m *DiscoveryResponse) GetDeploymentProfile() []*DeploymentProfileDTO {
	if m != nil {
		return m.DeploymentProfile
	}
	return nil
}

func (m *DiscoveryResponse) GetNotification() []*NotificationDTO {
	if m != nil {
		return m.Notification
	}
	return nil
}

func (m *DiscoveryResponse) GetMetadataDTO() []*CustomMetadataDTO {
	if m != nil {
		return m.MetadataDTO
	}
	return nil
}

func (m *DiscoveryResponse) GetDerivedTarget() []*DerivedTargetSpecificationDTO {
	if m != nil {
		return m.DerivedTarget
	}
	return nil
}

func (m *DiscoveryResponse) GetNonMarketEntityDTO() []*NonMarketEntityDTO {
	if m != nil {
		return m.NonMarketEntityDTO
	}
	return nil
}

func (m *DiscoveryResponse) GetFlowDTO() []*FlowDTO {
	if m != nil {
		return m.FlowDTO
	}
	return nil
}

func (m *DiscoveryResponse) GetDiscoveryContext() *DiscoveryContextDTO {
	if m != nil {
		return m.DiscoveryContext
	}
	return nil
}

func (m *DiscoveryResponse) GetCostDTO() []*CostDataDTO {
	if m != nil {
		return m.CostDTO
	}
	return nil
}

func (m *DiscoveryResponse) GetPriceTable() *PriceTable {
	if m != nil {
		return m.PriceTable
	}
	return nil
}

func (m *DiscoveryResponse) GetWorkflow() []*Workflow {
	if m != nil {
		return m.Workflow
	}
	return nil
}

func (m *DiscoveryResponse) GetNoChange() *NoChange {
	if m != nil {
		return m.NoChange
	}
	return nil
}

func (m *DiscoveryResponse) GetDiscActionSpec() *DiscoveredActionSpec {
	if m != nil {
		return m.DiscActionSpec
	}
	return nil
}

// Custom user-defined account values. These construction is used, when SDK probe writers
// define their own account values, instead of reusing existing ones.
// Custom fields should be used, when there is not predefined field to match the purpose
// of the field required by the probe.
type CustomAccountDefEntry struct {
	// The name of this entry field. The name must be unique for all of the entries you
	// define for this probe.
	Name *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	// The display name of this entry. This is the name that appears in the user interface.
	DisplayName *string `protobuf:"bytes,2,req,name=displayName" json:"displayName,omitempty"`
	// Optional description of what this entry represents.
	Description *string `protobuf:"bytes,3,req,name=description" json:"description,omitempty"`
	// A regular expression to validate a field. If the user's input matches the
	// regular expression, then the entry is valid.
	// For example, you can validate that the entered text is only numbers and period characters
	// for an IP address. To disable validation (allow any text), pass {@code ".*"}.
	VerificationRegex *string `protobuf:"bytes,4,opt,name=verificationRegex,def=.*" json:"verificationRegex,omitempty"`
	// Specifies if the value for the entry can be disclosed (in the log file or wherever else).
	IsSecret *bool `protobuf:"varint,5,opt,name=isSecret,def=0" json:"isSecret,omitempty"`
	// Field type describes, what data type is expected to be put into this field
	//
	// Types that are valid to be assigned to FieldType:
	//	*CustomAccountDefEntry_PrimitiveValue_
	//	*CustomAccountDefEntry_GroupScope
	//	*CustomAccountDefEntry_EntityScope
	FieldType        isCustomAccountDefEntry_FieldType `protobuf_oneof:"fieldType"`
	XXX_unrecognized []byte                            `json:"-"`
}

func (m *CustomAccountDefEntry) Reset()                    { *m = CustomAccountDefEntry{} }
func (m *CustomAccountDefEntry) String() string            { return proto.CompactTextString(m) }
func (*CustomAccountDefEntry) ProtoMessage()               {}
func (*CustomAccountDefEntry) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{7} }

const Default_CustomAccountDefEntry_VerificationRegex string = ".*"
const Default_CustomAccountDefEntry_IsSecret bool = false

type isCustomAccountDefEntry_FieldType interface {
	isCustomAccountDefEntry_FieldType()
}

type CustomAccountDefEntry_PrimitiveValue_ struct {
	PrimitiveValue CustomAccountDefEntry_PrimitiveValue `protobuf:"varint,6,opt,name=primitive_value,json=primitiveValue,enum=common_dto.CustomAccountDefEntry_PrimitiveValue,oneof"`
}
type CustomAccountDefEntry_GroupScope struct {
	GroupScope *CustomAccountDefEntry_GroupScopePropertySet `protobuf:"bytes,7,opt,name=group_scope,json=groupScope,oneof"`
}
type CustomAccountDefEntry_EntityScope struct {
	EntityScope *CustomAccountDefEntry_GroupScopePropertySet `protobuf:"bytes,8,opt,name=entity_scope,json=entityScope,oneof"`
}

func (*CustomAccountDefEntry_PrimitiveValue_) isCustomAccountDefEntry_FieldType() {}
func (*CustomAccountDefEntry_GroupScope) isCustomAccountDefEntry_FieldType()      {}
func (*CustomAccountDefEntry_EntityScope) isCustomAccountDefEntry_FieldType()     {}

func (m *CustomAccountDefEntry) GetFieldType() isCustomAccountDefEntry_FieldType {
	if m != nil {
		return m.FieldType
	}
	return nil
}

func (m *CustomAccountDefEntry) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *CustomAccountDefEntry) GetDisplayName() string {
	if m != nil && m.DisplayName != nil {
		return *m.DisplayName
	}
	return ""
}

func (m *CustomAccountDefEntry) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

func (m *CustomAccountDefEntry) GetVerificationRegex() string {
	if m != nil && m.VerificationRegex != nil {
		return *m.VerificationRegex
	}
	return Default_CustomAccountDefEntry_VerificationRegex
}

func (m *CustomAccountDefEntry) GetIsSecret() bool {
	if m != nil && m.IsSecret != nil {
		return *m.IsSecret
	}
	return Default_CustomAccountDefEntry_IsSecret
}

func (m *CustomAccountDefEntry) GetPrimitiveValue() CustomAccountDefEntry_PrimitiveValue {
	if x, ok := m.GetFieldType().(*CustomAccountDefEntry_PrimitiveValue_); ok {
		return x.PrimitiveValue
	}
	return CustomAccountDefEntry_STRING
}

func (m *CustomAccountDefEntry) GetGroupScope() *CustomAccountDefEntry_GroupScopePropertySet {
	if x, ok := m.GetFieldType().(*CustomAccountDefEntry_GroupScope); ok {
		return x.GroupScope
	}
	return nil
}

func (m *CustomAccountDefEntry) GetEntityScope() *CustomAccountDefEntry_GroupScopePropertySet {
	if x, ok := m.GetFieldType().(*CustomAccountDefEntry_EntityScope); ok {
		return x.EntityScope
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*CustomAccountDefEntry) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _CustomAccountDefEntry_OneofMarshaler, _CustomAccountDefEntry_OneofUnmarshaler, _CustomAccountDefEntry_OneofSizer, []interface{}{
		(*CustomAccountDefEntry_PrimitiveValue_)(nil),
		(*CustomAccountDefEntry_GroupScope)(nil),
		(*CustomAccountDefEntry_EntityScope)(nil),
	}
}

func _CustomAccountDefEntry_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*CustomAccountDefEntry)
	// fieldType
	switch x := m.FieldType.(type) {
	case *CustomAccountDefEntry_PrimitiveValue_:
		b.EncodeVarint(6<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.PrimitiveValue))
	case *CustomAccountDefEntry_GroupScope:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.GroupScope); err != nil {
			return err
		}
	case *CustomAccountDefEntry_EntityScope:
		b.EncodeVarint(8<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.EntityScope); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("CustomAccountDefEntry.FieldType has unexpected type %T", x)
	}
	return nil
}

func _CustomAccountDefEntry_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*CustomAccountDefEntry)
	switch tag {
	case 6: // fieldType.primitive_value
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.FieldType = &CustomAccountDefEntry_PrimitiveValue_{CustomAccountDefEntry_PrimitiveValue(x)}
		return true, err
	case 7: // fieldType.group_scope
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CustomAccountDefEntry_GroupScopePropertySet)
		err := b.DecodeMessage(msg)
		m.FieldType = &CustomAccountDefEntry_GroupScope{msg}
		return true, err
	case 8: // fieldType.entity_scope
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CustomAccountDefEntry_GroupScopePropertySet)
		err := b.DecodeMessage(msg)
		m.FieldType = &CustomAccountDefEntry_EntityScope{msg}
		return true, err
	default:
		return false, nil
	}
}

func _CustomAccountDefEntry_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*CustomAccountDefEntry)
	// fieldType
	switch x := m.FieldType.(type) {
	case *CustomAccountDefEntry_PrimitiveValue_:
		n += proto.SizeVarint(6<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(x.PrimitiveValue))
	case *CustomAccountDefEntry_GroupScope:
		s := proto.Size(x.GroupScope)
		n += proto.SizeVarint(7<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *CustomAccountDefEntry_EntityScope:
		s := proto.Size(x.EntityScope)
		n += proto.SizeVarint(8<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// Entity type with a set of properties for group scope account definition
type CustomAccountDefEntry_GroupScopePropertySet struct {
	// Entity type
	EntityType *EntityDTO_EntityType `protobuf:"varint,1,req,name=entityType,enum=common_dto.EntityDTO_EntityType" json:"entityType,omitempty"`
	// Set of properties
	Property         []*CustomAccountDefEntry_GroupScopeProperty `protobuf:"bytes,2,rep,name=property" json:"property,omitempty"`
	XXX_unrecognized []byte                                      `json:"-"`
}

func (m *CustomAccountDefEntry_GroupScopePropertySet) Reset() {
	*m = CustomAccountDefEntry_GroupScopePropertySet{}
}
func (m *CustomAccountDefEntry_GroupScopePropertySet) String() string {
	return proto.CompactTextString(m)
}
func (*CustomAccountDefEntry_GroupScopePropertySet) ProtoMessage() {}
func (*CustomAccountDefEntry_GroupScopePropertySet) Descriptor() ([]byte, []int) {
	return fileDescriptor3, []int{7, 0}
}

func (m *CustomAccountDefEntry_GroupScopePropertySet) GetEntityType() EntityDTO_EntityType {
	if m != nil && m.EntityType != nil {
		return *m.EntityType
	}
	return EntityDTO_SWITCH
}

func (m *CustomAccountDefEntry_GroupScopePropertySet) GetProperty() []*CustomAccountDefEntry_GroupScopeProperty {
	if m != nil {
		return m.Property
	}
	return nil
}

// Entity property for group scope selection
type CustomAccountDefEntry_GroupScopeProperty struct {
	// The name of the property
	PropertyName *string `protobuf:"bytes,1,req,name=propertyName" json:"propertyName,omitempty"`
	// Checks if property is mandatory or optional
	IsMandatory      *bool  `protobuf:"varint,2,opt,name=isMandatory,def=1" json:"isMandatory,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CustomAccountDefEntry_GroupScopeProperty) Reset() {
	*m = CustomAccountDefEntry_GroupScopeProperty{}
}
func (m *CustomAccountDefEntry_GroupScopeProperty) String() string { return proto.CompactTextString(m) }
func (*CustomAccountDefEntry_GroupScopeProperty) ProtoMessage()    {}
func (*CustomAccountDefEntry_GroupScopeProperty) Descriptor() ([]byte, []int) {
	return fileDescriptor3, []int{7, 1}
}

const Default_CustomAccountDefEntry_GroupScopeProperty_IsMandatory bool = true

func (m *CustomAccountDefEntry_GroupScopeProperty) GetPropertyName() string {
	if m != nil && m.PropertyName != nil {
		return *m.PropertyName
	}
	return ""
}

func (m *CustomAccountDefEntry_GroupScopeProperty) GetIsMandatory() bool {
	if m != nil && m.IsMandatory != nil {
		return *m.IsMandatory
	}
	return Default_CustomAccountDefEntry_GroupScopeProperty_IsMandatory
}

// The AccountDefinitionEntry class defines a single field that is part of the account credentials
// a user must specify to connect to a target of this probe type. Note that for every probe, the
// 'TARGET_IDENTIFIER' is a mandatory field.
//
// It's the responsibility of your probe to define the credentials it needs to attach to a target. When adding an associated target to
// Operations Manager via the REST API, the API call includes parameters for each of the credentials defined here.
// When attaching via the Operations Manager GUI, the credentials defined here appear in the GUI as individual fields.
// For a given probe, you define the credentials as a Set of AccountDefinitionEntry objects.
type AccountDefEntry struct {
	// Type of account definition
	//
	// Types that are valid to be assigned to Definition:
	//	*AccountDefEntry_PredefinedDefinition
	//	*AccountDefEntry_CustomDefinition
	Definition isAccountDefEntry_Definition `protobuf_oneof:"definition"`
	// Whether this field is mandatory (true) or optional (false). Default is mandatory
	Mandatory *bool `protobuf:"varint,4,opt,name=mandatory,def=1" json:"mandatory,omitempty"`
	// Default value the probe declares for this field. This can only be set if the field is
	// optional.
	DefaultValue *string `protobuf:"bytes,5,opt,name=defaultValue" json:"defaultValue,omitempty"`
	// Whether this field should be used as the display name.
	// If multiple fields have this attribute, the target display name will be the concatenation of them.
	// If no field has this attribute, the identifying fields in the probe info will be used.
	IsTargetDisplayName *bool `protobuf:"varint,6,opt,name=isTargetDisplayName,def=0" json:"isTargetDisplayName,omitempty"`
	// Values to which this field is allowed to be set. If empty, the field can be set to any value.
	AllowedValues    []string `protobuf:"bytes,7,rep,name=allowed_values,json=allowedValues" json:"allowed_values,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *AccountDefEntry) Reset()                    { *m = AccountDefEntry{} }
func (m *AccountDefEntry) String() string            { return proto.CompactTextString(m) }
func (*AccountDefEntry) ProtoMessage()               {}
func (*AccountDefEntry) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{8} }

const Default_AccountDefEntry_Mandatory bool = true
const Default_AccountDefEntry_IsTargetDisplayName bool = false

type isAccountDefEntry_Definition interface {
	isAccountDefEntry_Definition()
}

type AccountDefEntry_PredefinedDefinition struct {
	PredefinedDefinition string `protobuf:"bytes,2,opt,name=predefined_definition,json=predefinedDefinition,oneof"`
}
type AccountDefEntry_CustomDefinition struct {
	CustomDefinition *CustomAccountDefEntry `protobuf:"bytes,3,opt,name=custom_definition,json=customDefinition,oneof"`
}

func (*AccountDefEntry_PredefinedDefinition) isAccountDefEntry_Definition() {}
func (*AccountDefEntry_CustomDefinition) isAccountDefEntry_Definition()     {}

func (m *AccountDefEntry) GetDefinition() isAccountDefEntry_Definition {
	if m != nil {
		return m.Definition
	}
	return nil
}

func (m *AccountDefEntry) GetPredefinedDefinition() string {
	if x, ok := m.GetDefinition().(*AccountDefEntry_PredefinedDefinition); ok {
		return x.PredefinedDefinition
	}
	return ""
}

func (m *AccountDefEntry) GetCustomDefinition() *CustomAccountDefEntry {
	if x, ok := m.GetDefinition().(*AccountDefEntry_CustomDefinition); ok {
		return x.CustomDefinition
	}
	return nil
}

func (m *AccountDefEntry) GetMandatory() bool {
	if m != nil && m.Mandatory != nil {
		return *m.Mandatory
	}
	return Default_AccountDefEntry_Mandatory
}

func (m *AccountDefEntry) GetDefaultValue() string {
	if m != nil && m.DefaultValue != nil {
		return *m.DefaultValue
	}
	return ""
}

func (m *AccountDefEntry) GetIsTargetDisplayName() bool {
	if m != nil && m.IsTargetDisplayName != nil {
		return *m.IsTargetDisplayName
	}
	return Default_AccountDefEntry_IsTargetDisplayName
}

func (m *AccountDefEntry) GetAllowedValues() []string {
	if m != nil {
		return m.AllowedValues
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*AccountDefEntry) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _AccountDefEntry_OneofMarshaler, _AccountDefEntry_OneofUnmarshaler, _AccountDefEntry_OneofSizer, []interface{}{
		(*AccountDefEntry_PredefinedDefinition)(nil),
		(*AccountDefEntry_CustomDefinition)(nil),
	}
}

func _AccountDefEntry_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*AccountDefEntry)
	// definition
	switch x := m.Definition.(type) {
	case *AccountDefEntry_PredefinedDefinition:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.PredefinedDefinition)
	case *AccountDefEntry_CustomDefinition:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.CustomDefinition); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("AccountDefEntry.Definition has unexpected type %T", x)
	}
	return nil
}

func _AccountDefEntry_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*AccountDefEntry)
	switch tag {
	case 2: // definition.predefined_definition
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Definition = &AccountDefEntry_PredefinedDefinition{x}
		return true, err
	case 3: // definition.custom_definition
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CustomAccountDefEntry)
		err := b.DecodeMessage(msg)
		m.Definition = &AccountDefEntry_CustomDefinition{msg}
		return true, err
	default:
		return false, nil
	}
}

func _AccountDefEntry_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*AccountDefEntry)
	// definition
	switch x := m.Definition.(type) {
	case *AccountDefEntry_PredefinedDefinition:
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.PredefinedDefinition)))
		n += len(x.PredefinedDefinition)
	case *AccountDefEntry_CustomDefinition:
		s := proto.Size(x.CustomDefinition)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// Error DTO. Represent some errors, occurred during operations inside the Mediation Container.
type ErrorDTO struct {
	// Error severity. Used to specify the colour of the message, shown to the end user.
	Severity *ErrorDTO_ErrorSeverity `protobuf:"varint,1,req,name=severity,enum=common_dto.ErrorDTO_ErrorSeverity" json:"severity,omitempty"`
	// Error description. Should not be null.
	Description *string `protobuf:"bytes,2,req,name=description" json:"description,omitempty"`
	// UUID of the entity the error is related to, if any.
	EntityUuid *string `protobuf:"bytes,3,opt,name=entityUuid" json:"entityUuid,omitempty"`
	// Type of the entity the error is related to, if any.
	EntityType       *string `protobuf:"bytes,4,opt,name=entityType" json:"entityType,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ErrorDTO) Reset()                    { *m = ErrorDTO{} }
func (m *ErrorDTO) String() string            { return proto.CompactTextString(m) }
func (*ErrorDTO) ProtoMessage()               {}
func (*ErrorDTO) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{9} }

func (m *ErrorDTO) GetSeverity() ErrorDTO_ErrorSeverity {
	if m != nil && m.Severity != nil {
		return *m.Severity
	}
	return ErrorDTO_CRITICAL
}

func (m *ErrorDTO) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

func (m *ErrorDTO) GetEntityUuid() string {
	if m != nil && m.EntityUuid != nil {
		return *m.EntityUuid
	}
	return ""
}

func (m *ErrorDTO) GetEntityType() string {
	if m != nil && m.EntityType != nil {
		return *m.EntityType
	}
	return ""
}

// Custom Metadata DTO.
// Represents custom data that will used by the Operations Manager server for different features.
// Example : for injecting metadata for computing custom pricing for certain commodities.
type CustomMetadataDTO struct {
	// Namespace of the handler for this DTO in the server to handle the metadata
	Namespace *CustomTypeDef_MetadataNamespace `protobuf:"varint,1,req,name=namespace,enum=common_dto.CustomTypeDef_MetadataNamespace" json:"namespace,omitempty"`
	// Key in the namespace for the data
	Key *string `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
	// Type of data
	DataType *CustomMetadataDTO_Type `protobuf:"varint,3,req,name=dataType,enum=common_dto.CustomMetadataDTO_Type" json:"dataType,omitempty"`
	// Serializable Data
	Payload          *string `protobuf:"bytes,4,req,name=payload" json:"payload,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CustomMetadataDTO) Reset()                    { *m = CustomMetadataDTO{} }
func (m *CustomMetadataDTO) String() string            { return proto.CompactTextString(m) }
func (*CustomMetadataDTO) ProtoMessage()               {}
func (*CustomMetadataDTO) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{10} }

func (m *CustomMetadataDTO) GetNamespace() CustomTypeDef_MetadataNamespace {
	if m != nil && m.Namespace != nil {
		return *m.Namespace
	}
	return CustomTypeDef_UNKNOWN
}

func (m *CustomMetadataDTO) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *CustomMetadataDTO) GetDataType() CustomMetadataDTO_Type {
	if m != nil && m.DataType != nil {
		return *m.DataType
	}
	return CustomMetadataDTO_JSON
}

func (m *CustomMetadataDTO) GetPayload() string {
	if m != nil && m.Payload != nil {
		return *m.Payload
	}
	return ""
}

// Structure to hold account parameters, passed to probe to connect and authenticate
// to target.
type AccountValue struct {
	// Name of the parameter. Should refer to the "name" field of AccountDefEntry message,
	// which is returned by the probe in registration phase, for example "userName",
	// "password" and so on.
	Key *string `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	// String representation of the parameter value, for example "secretpassword",
	// "192.168.111.3" and so on.
	StringValue *string `protobuf:"bytes,2,opt,name=stringValue" json:"stringValue,omitempty"`
	// Set of property value lists
	GroupScopePropertyValues []*AccountValue_PropertyValueList `protobuf:"bytes,3,rep,name=groupScopePropertyValues" json:"groupScopePropertyValues,omitempty"`
	XXX_unrecognized         []byte                            `json:"-"`
}

func (m *AccountValue) Reset()                    { *m = AccountValue{} }
func (m *AccountValue) String() string            { return proto.CompactTextString(m) }
func (*AccountValue) ProtoMessage()               {}
func (*AccountValue) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{11} }

func (m *AccountValue) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *AccountValue) GetStringValue() string {
	if m != nil && m.StringValue != nil {
		return *m.StringValue
	}
	return ""
}

func (m *AccountValue) GetGroupScopePropertyValues() []*AccountValue_PropertyValueList {
	if m != nil {
		return m.GroupScopePropertyValues
	}
	return nil
}

type AccountValue_PropertyValueList struct {
	Value            []string `protobuf:"bytes,1,rep,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *AccountValue_PropertyValueList) Reset()         { *m = AccountValue_PropertyValueList{} }
func (m *AccountValue_PropertyValueList) String() string { return proto.CompactTextString(m) }
func (*AccountValue_PropertyValueList) ProtoMessage()    {}
func (*AccountValue_PropertyValueList) Descriptor() ([]byte, []int) {
	return fileDescriptor3, []int{11, 0}
}

func (m *AccountValue_PropertyValueList) GetValue() []string {
	if m != nil {
		return m.Value
	}
	return nil
}

// Use to create (or update) derived targets as a result of certain discovery.
type DerivedTargetSpecificationDTO struct {
	// String identifier to define the type of the probe.
	// If a probe of that type is not registered with the mediation container of current probe,
	// the derived target creation should fail.
	ProbeType *string `protobuf:"bytes,1,req,name=probeType" json:"probeType,omitempty"`
	// Account values provide entry data to the probe.
	// If for any of the keys of these values there is no account definition in the probe registered with probeType,
	// or this set is missing some mandatory account values, the derived target creation should fail.
	// When updating an existing target, all the values that do not constitute target identifier, should be updated.
	AccountValue []*AccountValue `protobuf:"bytes,2,rep,name=accountValue" json:"accountValue,omitempty"`
	// Whether the target should be visible in UI.
	// When an existing target is updated, this should be updated too.
	Hidden *bool `protobuf:"varint,3,opt,name=hidden,def=1" json:"hidden,omitempty"`
	// Whether the target should be created with dependence on the target being discovered.
	// When updating an existing target, it can change from independent to dependent.
	// But not from dependent to independent, or to dependent from another target.
	Dependent *bool `protobuf:"varint,4,opt,name=dependent,def=1" json:"dependent,omitempty"`
	// Whether the target cannot be changed through public APIs.
	Readonly         *bool  `protobuf:"varint,5,opt,name=readonly,def=0" json:"readonly,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *DerivedTargetSpecificationDTO) Reset()                    { *m = DerivedTargetSpecificationDTO{} }
func (m *DerivedTargetSpecificationDTO) String() string            { return proto.CompactTextString(m) }
func (*DerivedTargetSpecificationDTO) ProtoMessage()               {}
func (*DerivedTargetSpecificationDTO) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{12} }

const Default_DerivedTargetSpecificationDTO_Hidden bool = true
const Default_DerivedTargetSpecificationDTO_Dependent bool = true
const Default_DerivedTargetSpecificationDTO_Readonly bool = false

func (m *DerivedTargetSpecificationDTO) GetProbeType() string {
	if m != nil && m.ProbeType != nil {
		return *m.ProbeType
	}
	return ""
}

func (m *DerivedTargetSpecificationDTO) GetAccountValue() []*AccountValue {
	if m != nil {
		return m.AccountValue
	}
	return nil
}

func (m *DerivedTargetSpecificationDTO) GetHidden() bool {
	if m != nil && m.Hidden != nil {
		return *m.Hidden
	}
	return Default_DerivedTargetSpecificationDTO_Hidden
}

func (m *DerivedTargetSpecificationDTO) GetDependent() bool {
	if m != nil && m.Dependent != nil {
		return *m.Dependent
	}
	return Default_DerivedTargetSpecificationDTO_Dependent
}

func (m *DerivedTargetSpecificationDTO) GetReadonly() bool {
	if m != nil && m.Readonly != nil {
		return *m.Readonly
	}
	return Default_DerivedTargetSpecificationDTO_Readonly
}

// Discovery context is sent by the probe to the server and then returned back to the probe
// in the next discovery request. Discovery context contains a list of properties represented as
// name-value pairs.
type DiscoveryContextDTO struct {
	ContextEntry     map[string]string `protobuf:"bytes,1,rep,name=contextEntry" json:"contextEntry,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *DiscoveryContextDTO) Reset()                    { *m = DiscoveryContextDTO{} }
func (m *DiscoveryContextDTO) String() string            { return proto.CompactTextString(m) }
func (*DiscoveryContextDTO) ProtoMessage()               {}
func (*DiscoveryContextDTO) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{13} }

func (m *DiscoveryContextDTO) GetContextEntry() map[string]string {
	if m != nil {
		return m.ContextEntry
	}
	return nil
}

type NoChange struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *NoChange) Reset()                    { *m = NoChange{} }
func (m *NoChange) String() string            { return proto.CompactTextString(m) }
func (*NoChange) ProtoMessage()               {}
func (*NoChange) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{14} }

func init() {
	proto.RegisterType((*ValidationResponse)(nil), "common_dto.ValidationResponse")
	proto.RegisterType((*ActionMergeSpec)(nil), "common_dto.ActionMergeSpec")
	proto.RegisterType((*ProvisionTransformSpec)(nil), "common_dto.ProvisionTransformSpec")
	proto.RegisterType((*MoveTransformSpec)(nil), "common_dto.MoveTransformSpec")
	proto.RegisterType((*ResizeTransformSpec)(nil), "common_dto.ResizeTransformSpec")
	proto.RegisterType((*DiscoveredActionSpec)(nil), "common_dto.DiscoveredActionSpec")
	proto.RegisterType((*DiscoveryResponse)(nil), "common_dto.DiscoveryResponse")
	proto.RegisterType((*CustomAccountDefEntry)(nil), "common_dto.CustomAccountDefEntry")
	proto.RegisterType((*CustomAccountDefEntry_GroupScopePropertySet)(nil), "common_dto.CustomAccountDefEntry.GroupScopePropertySet")
	proto.RegisterType((*CustomAccountDefEntry_GroupScopeProperty)(nil), "common_dto.CustomAccountDefEntry.GroupScopeProperty")
	proto.RegisterType((*AccountDefEntry)(nil), "common_dto.AccountDefEntry")
	proto.RegisterType((*ErrorDTO)(nil), "common_dto.ErrorDTO")
	proto.RegisterType((*CustomMetadataDTO)(nil), "common_dto.CustomMetadataDTO")
	proto.RegisterType((*AccountValue)(nil), "common_dto.AccountValue")
	proto.RegisterType((*AccountValue_PropertyValueList)(nil), "common_dto.AccountValue.PropertyValueList")
	proto.RegisterType((*DerivedTargetSpecificationDTO)(nil), "common_dto.DerivedTargetSpecificationDTO")
	proto.RegisterType((*DiscoveryContextDTO)(nil), "common_dto.DiscoveryContextDTO")
	proto.RegisterType((*NoChange)(nil), "common_dto.NoChange")
	proto.RegisterEnum("common_dto.DiscoveryType", DiscoveryType_name, DiscoveryType_value)
	proto.RegisterEnum("common_dto.CustomAccountDefEntry_PrimitiveValue", CustomAccountDefEntry_PrimitiveValue_name, CustomAccountDefEntry_PrimitiveValue_value)
	proto.RegisterEnum("common_dto.ErrorDTO_ErrorSeverity", ErrorDTO_ErrorSeverity_name, ErrorDTO_ErrorSeverity_value)
	proto.RegisterEnum("common_dto.CustomMetadataDTO_Type", CustomMetadataDTO_Type_name, CustomMetadataDTO_Type_value)
}

func init() { proto.RegisterFile("Discovery.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 1672 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x57, 0xdd, 0x6e, 0x1b, 0xb9,
	0x15, 0xb6, 0x7e, 0x6c, 0x4b, 0x47, 0x3f, 0x96, 0x68, 0x7b, 0x3b, 0x75, 0x93, 0x5d, 0xed, 0x14,
	0x5d, 0x78, 0xdd, 0x5d, 0x21, 0x76, 0xdb, 0xa4, 0x70, 0x8a, 0xa4, 0xb2, 0x24, 0xc7, 0x4a, 0x2d,
	0xc9, 0xa0, 0xe5, 0xa4, 0x7f, 0x80, 0x3a, 0x9e, 0xa1, 0x94, 0x41, 0xa4, 0xe1, 0x80, 0x43, 0x29,
	0x51, 0xdf, 0xa0, 0xcf, 0x52, 0x14, 0xe8, 0x4d, 0xdf, 0xa3, 0x37, 0x05, 0x7a, 0x55, 0xf4, 0xa6,
	0xef, 0x51, 0x90, 0x9c, 0x5f, 0x8d, 0xd2, 0xa0, 0xd9, 0x1b, 0x7b, 0x78, 0xce, 0xf7, 0x7d, 0x24,
	0x0f, 0xcf, 0x39, 0xa4, 0x60, 0xaf, 0x63, 0x7b, 0x26, 0x5d, 0x12, 0xb6, 0x6a, 0xba, 0x8c, 0x72,
	0x8a, 0xc0, 0xa4, 0xf3, 0x39, 0x75, 0xc6, 0x16, 0xa7, 0x47, 0x7b, 0x6d, 0xf9, 0xdd, 0x19, 0x0d,
	0x95, 0xf3, 0xa8, 0x76, 0xc3, 0xe8, 0xc4, 0x9e, 0x91, 0xc8, 0xa2, 0x0d, 0xa8, 0xd3, 0x37, 0xd8,
	0x5b, 0xc2, 0xbb, 0x0e, 0xb7, 0xf9, 0x2a, 0x81, 0xb5, 0x4d, 0xdb, 0x99, 0x46, 0x96, 0xc3, 0x96,
	0xc9, 0x6d, 0xea, 0x74, 0xdf, 0x13, 0x73, 0x21, 0x3e, 0x94, 0x59, 0xbf, 0x04, 0xf4, 0xca, 0x98,
	0xd9, 0x96, 0x21, 0x6c, 0x98, 0x78, 0x2e, 0x75, 0x3c, 0x82, 0x1e, 0x41, 0x81, 0x30, 0x46, 0x59,
	0x67, 0x34, 0xd4, 0x32, 0x8d, 0xdc, 0x71, 0xe9, 0xec, 0xa0, 0x19, 0x2d, 0xad, 0xd9, 0xf5, 0x7d,
	0x38, 0x44, 0xe9, 0xff, 0xca, 0xc2, 0x9e, 0x9a, 0xa1, 0x4f, 0xd8, 0x94, 0xdc, 0xba, 0xc4, 0x44,
	0x0f, 0x01, 0x88, 0x5c, 0xd7, 0xd8, 0xb6, 0x3c, 0xa9, 0x53, 0xc4, 0x45, 0x65, 0xe9, 0x59, 0x1e,
	0xfa, 0x21, 0x54, 0xb8, 0xc1, 0xa6, 0x84, 0x8f, 0x95, 0x4d, 0xcb, 0x36, 0x32, 0xc7, 0x45, 0x5c,
	0x56, 0x46, 0xb5, 0x23, 0xf4, 0x2d, 0x20, 0x1f, 0x64, 0x11, 0xcf, 0x64, 0xb6, 0x2b, 0xa6, 0xd0,
	0x72, 0x12, 0x59, 0x57, 0x9e, 0x4e, 0xe4, 0x40, 0x4f, 0xa1, 0x30, 0xa7, 0x4b, 0x39, 0xbd, 0x96,
	0x6f, 0x64, 0x8e, 0x4b, 0x67, 0x0f, 0xe3, 0x0b, 0xef, 0xd3, 0x25, 0x19, 0x31, 0xc3, 0xf1, 0x26,
	0x94, 0xcd, 0x05, 0xe8, 0x6a, 0x0b, 0x87, 0x04, 0xd4, 0x02, 0x60, 0xc4, 0xb3, 0xff, 0xa8, 0xe8,
	0xdb, 0x92, 0xfe, 0x45, 0x9c, 0x8e, 0xa5, 0x77, 0x5d, 0x20, 0x46, 0x42, 0x2f, 0xa1, 0xe2, 0x32,
	0xba, 0xb4, 0x3d, 0x9b, 0x3a, 0x52, 0x65, 0x47, 0xaa, 0xe8, 0x71, 0x95, 0x9b, 0x00, 0xb0, 0x2e,
	0x94, 0xa4, 0x5e, 0x94, 0x01, 0x0c, 0x19, 0x51, 0x31, 0xd2, 0x35, 0xf8, 0x6c, 0x33, 0x51, 0xff,
	0x0d, 0xd4, 0x53, 0xfb, 0x42, 0x1d, 0x28, 0x4b, 0x35, 0x8b, 0xb0, 0xd1, 0xca, 0x25, 0x5a, 0xa6,
	0x91, 0x3d, 0xae, 0x9e, 0x35, 0x12, 0xa7, 0x18, 0xe6, 0x8c, 0xfa, 0x12, 0x38, 0x9c, 0x60, 0xe9,
	0x7f, 0xcb, 0xc0, 0xfe, 0x86, 0x4d, 0xa3, 0x3e, 0x54, 0xa5, 0x90, 0x25, 0x0e, 0x97, 0x2b, 0xfd,
	0xdc, 0x71, 0xf5, 0xec, 0xab, 0xb8, 0x7e, 0x3b, 0x40, 0x88, 0x29, 0xc2, 0x81, 0x9c, 0xa5, 0x62,
	0xc6, 0x87, 0x68, 0x08, 0x65, 0xf3, 0x8d, 0xe1, 0x4c, 0x89, 0x35, 0x36, 0x38, 0x67, 0x5a, 0x56,
	0x8a, 0x7d, 0x13, 0x17, 0x53, 0xb9, 0xd5, 0xe3, 0x64, 0x9e, 0x50, 0x6b, 0x71, 0xce, 0xec, 0xfb,
	0x05, 0x27, 0xb8, 0xe4, 0x2b, 0x08, 0x8b, 0xde, 0x83, 0x83, 0xa0, 0xb4, 0x88, 0xd5, 0x0a, 0x83,
	0x88, 0x4e, 0x61, 0xdb, 0x73, 0x89, 0xe9, 0xf9, 0x49, 0xfd, 0x83, 0xf4, 0x0c, 0x61, 0xf6, 0x62,
	0x85, 0xd4, 0xff, 0x54, 0x80, 0x7a, 0x58, 0xa6, 0x9f, 0x5e, 0x20, 0xe8, 0x27, 0xe0, 0xa7, 0xbe,
	0xa0, 0x64, 0x25, 0xe5, 0x70, 0xe3, 0x69, 0xe0, 0x08, 0x87, 0x9e, 0xc1, 0x9e, 0x15, 0xee, 0xe3,
	0x05, 0xa3, 0x0b, 0x57, 0xcb, 0xa5, 0x67, 0x93, 0x0e, 0xc1, 0x5c, 0x07, 0xa3, 0x0b, 0xa8, 0x28,
	0x31, 0xbf, 0x75, 0x68, 0x79, 0xc9, 0x7e, 0x90, 0x9e, 0x38, 0xea, 0x2d, 0x38, 0x49, 0x41, 0x03,
	0xa8, 0x5b, 0xc4, 0x9d, 0xd1, 0xd5, 0x9c, 0x38, 0x3c, 0xd0, 0xd9, 0x96, 0x3a, 0x89, 0x74, 0xea,
	0xac, 0x83, 0x84, 0x56, 0x9a, 0x8a, 0x9e, 0x43, 0xd9, 0xa1, 0xdc, 0x9e, 0xd8, 0xa6, 0xec, 0x39,
	0xda, 0x4e, 0xfa, 0x28, 0x06, 0x31, 0xbf, 0x50, 0x49, 0x10, 0xd0, 0x73, 0x28, 0xcd, 0x09, 0x37,
	0x2c, 0x83, 0x1b, 0x22, 0x96, 0xbb, 0x92, 0x9f, 0x28, 0xf3, 0xf6, 0xc2, 0xe3, 0x74, 0xde, 0x8f,
	0x40, 0x38, 0xce, 0x40, 0x43, 0xa8, 0x58, 0x84, 0xd9, 0x4b, 0x62, 0x8d, 0x64, 0x03, 0xd1, 0x0a,
	0x52, 0xe2, 0xeb, 0xe4, 0x6e, 0x62, 0x00, 0x91, 0x0f, 0x89, 0x05, 0x25, 0xf9, 0x68, 0x00, 0xc8,
	0x49, 0x75, 0x62, 0xad, 0x28, 0x55, 0x3f, 0x4f, 0x6e, 0x6c, 0x1d, 0x85, 0x37, 0x30, 0xd1, 0xb7,
	0xb0, 0x3b, 0x99, 0xd1, 0x77, 0x42, 0xa4, 0x24, 0x45, 0xf6, 0xe3, 0x22, 0x97, 0xca, 0x85, 0x03,
	0x0c, 0xfa, 0x15, 0xd4, 0x82, 0x83, 0x5f, 0xb5, 0xa9, 0xc3, 0xc9, 0x7b, 0xae, 0x95, 0xd3, 0xdd,
	0xab, 0xb3, 0x86, 0x11, 0x1a, 0x29, 0x22, 0x3a, 0x85, 0x5d, 0x93, 0x7a, 0xc2, 0xa9, 0x55, 0xe4,
	0xdc, 0xdf, 0x4b, 0xd6, 0xb4, 0xc7, 0x3b, 0x7e, 0x4c, 0x03, 0x1c, 0x7a, 0x0c, 0xe0, 0x32, 0xdb,
	0x24, 0x23, 0xe3, 0x7e, 0x46, 0xb4, 0xaa, 0x9c, 0xf9, 0xb3, 0x64, 0xc7, 0x0b, 0xbc, 0x38, 0x86,
	0x14, 0x45, 0xf4, 0x8e, 0xb2, 0xb7, 0x62, 0x1b, 0xda, 0x5e, 0x3a, 0xad, 0x5f, 0xfb, 0x3e, 0x1c,
	0xa2, 0xd0, 0x29, 0x14, 0x1d, 0x3a, 0x56, 0x95, 0xae, 0xd5, 0xe4, 0x44, 0x07, 0xc9, 0xf8, 0xb6,
	0xa5, 0x0f, 0x17, 0x1c, 0xff, 0x0b, 0xbd, 0x54, 0xc1, 0x19, 0xab, 0x56, 0x3a, 0x16, 0x45, 0xad,
	0xd5, 0x25, 0xb3, 0xb1, 0x29, 0x38, 0xf1, 0x76, 0x81, 0xab, 0x82, 0x19, 0x8d, 0xf5, 0xbf, 0xee,
	0xc0, 0xa1, 0xca, 0xad, 0x96, 0x69, 0xd2, 0x85, 0xc3, 0x3b, 0x64, 0xd2, 0x75, 0x38, 0x5b, 0x21,
	0x04, 0x79, 0xc7, 0x98, 0xab, 0x36, 0x5b, 0xc4, 0xf2, 0x1b, 0x35, 0xa0, 0x64, 0xd9, 0x9e, 0x3b,
	0x33, 0x56, 0x03, 0xe1, 0xca, 0x4a, 0x57, 0xdc, 0x24, 0x11, 0x89, 0x5b, 0x4d, 0x21, 0x62, 0xf7,
	0xd9, 0x23, 0xa8, 0x2f, 0x09, 0x0b, 0x73, 0x0f, 0x93, 0x29, 0x79, 0x2f, 0x2f, 0xb6, 0xe2, 0x79,
	0xb6, 0x79, 0x82, 0xd3, 0x4e, 0xf4, 0x25, 0x14, 0x6c, 0xef, 0x96, 0x98, 0x8c, 0x70, 0x79, 0x85,
	0x15, 0xce, 0xb7, 0x27, 0xc6, 0xcc, 0x23, 0x38, 0x34, 0xa3, 0xdf, 0xc1, 0x9e, 0xcb, 0xec, 0xb9,
	0xcd, 0xed, 0x25, 0x19, 0x2f, 0x8d, 0xd9, 0x82, 0xc8, 0x6b, 0xaa, 0x7a, 0xf6, 0x28, 0x5d, 0x44,
	0x6b, 0x1b, 0x15, 0x47, 0xa9, 0x88, 0xaf, 0x04, 0xef, 0x6a, 0x0b, 0x57, 0xdd, 0x84, 0x05, 0xfd,
	0x16, 0x4a, 0x53, 0xd1, 0x7b, 0xc6, 0x9e, 0x49, 0x5d, 0xa2, 0xed, 0xca, 0x50, 0x3f, 0xf9, 0xb8,
	0xb0, 0x6c, 0x58, 0xb7, 0x82, 0x73, 0xc3, 0xa8, 0x4b, 0x18, 0x5f, 0xdd, 0x12, 0x2e, 0x6e, 0xd7,
	0x69, 0xe8, 0x40, 0xbf, 0x87, 0xb2, 0xff, 0xa0, 0x50, 0xe2, 0x85, 0xef, 0x2a, 0x5e, 0x52, 0x72,
	0xd2, 0x73, 0xf4, 0xe7, 0x0c, 0x1c, 0x6e, 0x04, 0xa2, 0x5f, 0x06, 0x0f, 0x99, 0xff, 0xeb, 0x2a,
	0x8d, 0x71, 0xd0, 0x0d, 0x14, 0x5c, 0x5f, 0xd0, 0x6f, 0xfe, 0x3f, 0xfd, 0x94, 0x55, 0xe3, 0x50,
	0xe5, 0xe8, 0x0f, 0x80, 0xd2, 0x7e, 0xa4, 0xcb, 0x6b, 0x5f, 0x7e, 0x0f, 0xa2, 0x7c, 0x4c, 0xd8,
	0xd0, 0x57, 0x50, 0xb2, 0xbd, 0xbe, 0xe1, 0x58, 0x06, 0xa7, 0x4c, 0xbd, 0xba, 0x0a, 0xe7, 0x79,
	0xce, 0x16, 0x04, 0xc7, 0x1d, 0xfa, 0x63, 0xa8, 0x26, 0x4f, 0x1b, 0x01, 0xec, 0xdc, 0x8e, 0x70,
	0x6f, 0xf0, 0xa2, 0x96, 0x41, 0x25, 0xd8, 0x1d, 0xdc, 0xf5, 0xbb, 0xb8, 0xd7, 0xae, 0x65, 0xc5,
	0xe0, 0x62, 0x38, 0xbc, 0xee, 0xb6, 0x06, 0xb5, 0xdc, 0x45, 0x09, 0x8a, 0x13, 0x9b, 0xcc, 0x2c,
	0xf9, 0x82, 0xf8, 0xbb, 0x7c, 0x17, 0x26, 0x8b, 0xe5, 0x67, 0x70, 0xe8, 0x32, 0x62, 0x91, 0x89,
	0xed, 0x10, 0x6b, 0x2c, 0xff, 0xdb, 0xb2, 0x00, 0xe4, 0x03, 0xf0, 0x6a, 0x0b, 0x1f, 0x44, 0xee,
	0x4e, 0xe8, 0x45, 0x37, 0x50, 0x37, 0x65, 0x9c, 0xe2, 0x94, 0x9c, 0x4c, 0x81, 0x2f, 0x3f, 0x1a,
	0xcc, 0xab, 0x2d, 0x5c, 0x53, 0xec, 0x98, 0xa2, 0x0e, 0xc5, 0x79, 0x18, 0x87, 0x7c, 0x2c, 0x0e,
	0x91, 0x59, 0x44, 0xd4, 0x22, 0x13, 0x63, 0x31, 0xe3, 0x32, 0x06, 0xb2, 0xa6, 0x8a, 0x38, 0x61,
	0x43, 0x4f, 0x60, 0xdf, 0xf6, 0xd4, 0x5d, 0xd0, 0x89, 0x55, 0xfc, 0x4e, 0xbc, 0xfc, 0x36, 0x21,
	0xd0, 0x8f, 0xa0, 0x6a, 0xcc, 0x66, 0xf4, 0x1d, 0xb1, 0x54, 0x1d, 0x7a, 0xf2, 0x36, 0x2b, 0xe2,
	0x8a, 0x6f, 0x95, 0xf2, 0x9e, 0x78, 0x09, 0x46, 0x5b, 0xd6, 0xff, 0x99, 0x81, 0x42, 0xf0, 0xc0,
	0x40, 0xcf, 0xa0, 0xe0, 0x11, 0xd1, 0x05, 0xf8, 0xca, 0x4f, 0x4c, 0x7d, 0xd3, 0x43, 0x44, 0x7d,
	0xdc, 0xfa, 0x48, 0x1c, 0x72, 0xd6, 0x5b, 0x50, 0x36, 0xdd, 0x82, 0x3e, 0x0f, 0x92, 0xff, 0x6e,
	0x61, 0x5b, 0xfe, 0xcb, 0x3b, 0x66, 0x89, 0xfc, 0xb2, 0x38, 0xf2, 0x71, 0xbf, 0xcc, 0x80, 0x13,
	0xa8, 0x24, 0x26, 0x47, 0x65, 0x28, 0xb4, 0x71, 0x6f, 0xd4, 0x6b, 0xb7, 0xae, 0x6b, 0x5b, 0x22,
	0x75, 0x5e, 0xb7, 0xf0, 0x40, 0x26, 0x95, 0xfe, 0x9f, 0x0c, 0xd4, 0x53, 0x97, 0x37, 0xea, 0x41,
	0x51, 0x34, 0x54, 0xcf, 0x35, 0xcc, 0xa0, 0xfa, 0x7e, 0x9c, 0x3e, 0x70, 0x31, 0x59, 0x87, 0x4c,
	0x9a, 0x01, 0x73, 0x10, 0x50, 0x70, 0xc4, 0x46, 0x35, 0xc8, 0xbd, 0x25, 0xc1, 0x2f, 0x0d, 0xf1,
	0x29, 0x02, 0x28, 0xd0, 0x72, 0xf1, 0xb9, 0x74, 0x00, 0x53, 0xab, 0x69, 0xca, 0xda, 0x0e, 0x39,
	0x48, 0x83, 0x5d, 0xd7, 0x58, 0xcd, 0xa8, 0x61, 0x69, 0x79, 0x19, 0xbc, 0x60, 0xa8, 0x7f, 0x1f,
	0xf2, 0x12, 0x51, 0x80, 0xfc, 0xcb, 0xdb, 0xe1, 0xa0, 0xb6, 0x85, 0x76, 0x21, 0xf7, 0xeb, 0xfe,
	0x75, 0x2d, 0xa3, 0xff, 0x23, 0x03, 0x65, 0x3f, 0x41, 0x55, 0x06, 0xf9, 0xeb, 0x52, 0xe5, 0x2a,
	0xd7, 0xd5, 0x80, 0x92, 0xc7, 0x99, 0xed, 0x4c, 0x55, 0xda, 0xa9, 0x15, 0xc7, 0x4d, 0x68, 0x02,
	0xda, 0x34, 0xd5, 0x01, 0x54, 0xc6, 0xf8, 0xaf, 0xc4, 0x93, 0xe4, 0xfb, 0x36, 0x9a, 0xaf, 0x99,
	0x80, 0x5f, 0xdb, 0x1e, 0xc7, 0x1f, 0xd4, 0x3a, 0xfa, 0x1a, 0xea, 0x29, 0x38, 0x3a, 0x80, 0x6d,
	0x75, 0x73, 0xa8, 0x9f, 0x75, 0x6a, 0xa0, 0xff, 0x3b, 0x03, 0x0f, 0xff, 0xe7, 0xcb, 0x09, 0x3d,
	0x80, 0xa2, 0xcb, 0xe8, 0x3d, 0x09, 0x3b, 0x69, 0x11, 0x47, 0x06, 0xf4, 0x0b, 0x28, 0x1b, 0xb1,
	0x65, 0xfa, 0xad, 0x52, 0xfb, 0xd0, 0x36, 0x70, 0x02, 0x8d, 0x1e, 0xc0, 0xce, 0x1b, 0xdb, 0xb2,
	0x88, 0xea, 0x0a, 0x41, 0x2d, 0xfb, 0x36, 0x51, 0xec, 0x16, 0x71, 0x89, 0x63, 0x11, 0x87, 0x27,
	0x8b, 0x3d, 0x34, 0x8b, 0xcb, 0x93, 0x11, 0xc3, 0xa2, 0xce, 0x6c, 0xb5, 0x76, 0x79, 0x06, 0x66,
	0xfd, 0x2f, 0x19, 0xd8, 0xdf, 0xf0, 0x92, 0x42, 0x77, 0x50, 0x36, 0xd5, 0x48, 0xf6, 0x1b, 0xff,
	0x57, 0xc1, 0xe9, 0x47, 0x1e, 0x60, 0xcd, 0x76, 0x8c, 0x23, 0xff, 0xe0, 0x84, 0xcc, 0xd1, 0x73,
	0xa8, 0xa7, 0x20, 0x51, 0xb6, 0x84, 0x59, 0x1c, 0x1e, 0x87, 0xca, 0x13, 0x35, 0x38, 0xcf, 0xfe,
	0x3c, 0xa3, 0x03, 0x14, 0x82, 0x57, 0xd1, 0xc9, 0x53, 0xa8, 0x84, 0x6b, 0x08, 0x52, 0xf3, 0xf2,
	0xee, 0x5a, 0x94, 0xe1, 0x1e, 0x94, 0x7a, 0x83, 0x36, 0xee, 0xf6, 0xbb, 0x83, 0x51, 0xeb, 0xba,
	0x96, 0x11, 0x86, 0x9b, 0x2e, 0xbe, 0x1c, 0xe2, 0x7e, 0x6b, 0xd0, 0xee, 0xd6, 0xb2, 0x17, 0xdf,
	0xc0, 0x17, 0x26, 0x9d, 0x37, 0x97, 0x73, 0xbe, 0x60, 0xf7, 0xb4, 0xe9, 0xce, 0x0c, 0x2e, 0x7e,
	0x0f, 0xfa, 0x1b, 0x6c, 0x5a, 0x9c, 0x5e, 0x14, 0x43, 0xf5, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff,
	0xc4, 0x35, 0x87, 0x90, 0xdb, 0x10, 0x00, 0x00,
}
